# Generated by Django 5.1.3 on 2026-09-19 15:56

import account.validators
import common.validators
import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, validators=[account.validators.validate_username])),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text="Bron yoki ariza berishda so'raladi. Takrorlanishi mumkin.", max_length=13, null=True, validators=[account.validators.validate_phone_number], verbose_name='Aloqa raqami')),
                ('google_sub', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Google ID')),
                ('role', models.CharField(choices=[('user', 'Oddiy foydalanuvchi'), ('business', 'Biznes admin'), ('admin', 'Platforma admini')], db_index=True, default='user', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[common.validators.validate_image_file], verbose_name='Profil rasmi')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='Qisqacha')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('preferred_language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2, verbose_name='Interfeys tili')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Raqam kiritilgan')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('has_used_trial', models.BooleanField(default=False, help_text='Bir marta berilgach qaytarilmaydi.', verbose_name='Bepul sinov ishlatilgan')),
                ('trust_bits', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='1–100. Yangi hisob 100 Bit bilan boshlanadi.', verbose_name='Ishonchlilik (Bit)')),
                ('cancelled_reservations_count', models.PositiveIntegerField(default=0, help_text="Faqat foydalanuvchining O'ZI bekor qilganlari. Joy egasi rad etgan bronlar bu yerga qo'shilmaydi.", verbose_name='Bekor qilgan bronlari')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['role', 'is_active'], name='idx_user_role_active'), models.Index(fields=['phone_number'], name='idx_user_phone'), models.Index(fields=['trust_bits'], name='idx_user_trust_bits')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
