# Generated by Django 5.1.3 on 2026-09-19 15:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_telegram_username', models.CharField(default='akobir_marupov', help_text="@ belgisiz kiriting. Business ariza/to'lov oqimida foydalanuvchiga shu ko'rsatiladi.", max_length=32)),
                ('support_phone', models.CharField(blank=True, default='+998771210418', max_length=20)),
                ('room_deposit_premium', models.DecimalField(decimal_places=2, default=Decimal('99000'), help_text="Restoran Premium xonasi uchun oldindan to'lov.", max_digits=12)),
                ('room_deposit_pro', models.DecimalField(decimal_places=2, default=Decimal('49000'), help_text="Restoran Pro xonasi uchun oldindan to'lov.", max_digits=12)),
                ('venue_deposit', models.DecimalField(decimal_places=2, default=Decimal('599000'), help_text="To'yxona zalini bron qilishda oldindan to'lov.", max_digits=12)),
                ('trial_days', models.PositiveSmallIntegerField(default=7)),
                ('subscription_days', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Platforma sozlamalari',
                'verbose_name_plural': 'Platforma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('idea', 'Taklif'), ('problem', 'Muammo'), ('other', 'Boshqa')], db_index=True, default='idea', max_length=10, verbose_name='Turi')),
                ('message', models.TextField(max_length=1000, verbose_name='Matn')),
                ('page', models.CharField(blank=True, max_length=200, verbose_name='Qaysi sahifadan')),
                ('contact', models.CharField(blank=True, help_text="Telefon yoki Telegram — javob kerak bo'lsa.", max_length=120, verbose_name='Aloqa (ixtiyoriy)')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('seen', "O'qilgan"), ('done', 'Hal qilingan')], db_index=True, default='new', max_length=10, verbose_name='Holati')),
                ('admin_note', models.TextField(blank=True, help_text="Faqat ichki foydalanish uchun — foydalanuvchiga ko'rinmaydi.", verbose_name='Administrator izohi')),
                ('user', models.ForeignKey(blank=True, help_text="Bo'sh — kirmagan foydalanuvchi yozgan.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Kim yozgan')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_feedback_status_created')],
            },
        ),
    ]
