# Generated by Django 5.2.17 on 2026-09-19 19:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='subscription_days',
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='room_deposit_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('99000'), help_text="Restoran Premium xonasi uchun oldindan to'lov.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='room_deposit_pro',
            field=models.DecimalField(decimal_places=2, default=Decimal('49000'), help_text="Restoran Pro xonasi uchun oldindan to'lov.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Yangi biznesga beriladigan bepul sinov muddati. Pullik obuna muddati esa tarif rejasidan olinadi.', verbose_name='Bepul sinov (kun)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='venue_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('599000'), help_text="To'yxona zalini bron qilishda oldindan to'lov.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
