# Generated by Django 5.2.17 on 2026-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_platformsettings_subscription_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='subscription_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Standart obuna muddati. Aniq muddat tarif rejasidan olinadi.', verbose_name='Obuna muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Yangi biznesga beriladigan bepul sinov muddati.', verbose_name='Bepul sinov (kun)'),
        ),
    ]
