# Generated by Django 5.1.3 on 2026-09-19 15:56

import account.validators
import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='business_photos/', validators=[common.validators.validate_image_file])),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Karuseldagi tartib.')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('people', models.PositiveIntegerField(help_text='Zaldagi odamlar soni (masalan: 200, 500)', validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='halls/', validators=[common.validators.validate_image_file])),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('all_price', models.DecimalField(blank=True, decimal_places=2, help_text="Butun zal uchun bir kunlik qat'iy summa (masalan 15 000 000). Qishloq to'yxonalarida narx odatda shunday: kishi boshiga emas, kunlik ijara. Bo'sh qoldirilsa mijozga narx ko'rsatilmaydi.", max_digits=14, null=True, verbose_name='Bir kunlik ijara narxi')),
                ('deposit_price', models.DecimalField(blank=True, decimal_places=2, help_text="Bron qilishda oldindan to'lov. Bo'sh qoldirilsa platforma standarti olinadi.", max_digits=12, null=True)),
            ],
            options={
                'ordering': ['-people', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('vip', 'VIP xona'), ('standard', 'Oddiy zal'), ('outdoor', 'Tashqi terrasa')], db_index=True, max_length=15)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rooms/', validators=[common.validators.validate_image_file])),
                ('deposit_tier', models.CharField(blank=True, choices=[('premium', 'Premium'), ('pro', 'Pro')], help_text="Faqat restoranlar uchun. To'yxona zallarida bo'sh qoldiring.", max_length=10, null=True)),
                ('deposit_price', models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa, tarifning platformadagi standart narxi olinadi.", max_digits=12, null=True)),
            ],
            options={
                'ordering': ['capacity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenuePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish_count', models.PositiveSmallIntegerField(choices=[(1, '1 xil taom'), (2, '2 xil taom'), (3, '3 xil taom')])),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['dish_count'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restoran'), ('venue', "To'yxona")], db_index=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, db_index=True, help_text='Tuman — qidiruvda nom bilan birga ishlatiladi (masalan: Yunusobod).', max_length=100)),
                ('latitude', models.FloatField(default=0, validators=[common.validators.validate_latitude])),
                ('longitude', models.FloatField(default=0, validators=[common.validators.validate_longitude])),
                ('map_link', models.URLField(blank=True, help_text='Google Maps yoki Yandex Xaritadan "ulashish" havolasini shu yerga qo\'ying. Koordinatalar undan avtomatik olinadi.', max_length=500, verbose_name='Xaritadagi havola')),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='business_covers/', validators=[common.validators.validate_image_file])),
                ('cuisine', models.CharField(blank=True, choices=[('milliy', 'Milliy taomlar'), ('yevropa', 'Yevropa oshxonasi'), ('fusion', 'Fusion'), ('sharqona', 'Sharqona'), ('fastfood', 'Fast food'), ('boshqa', 'Boshqa')], db_index=True, help_text='Faqat restoranlar uchun oshxona turi.', max_length=20)),
                ('open_time', models.TimeField(blank=True, help_text='Ish boshlanish vaqti (restoran).', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Ish tugash vaqti (restoran).', null=True)),
                ('telegram_username', models.CharField(blank=True, help_text="@ belgisiz. Mijoz depozit to'lovi uchun shu manzilga yozadi. Faqat ro'yxatdan o'tgan foydalanuvchilarga ko'rinadi.", max_length=32)),
                ('phone_number', models.CharField(blank=True, help_text="+998XXXXXXXXX. Faqat ro'yxatdan o'tgan foydalanuvchilarga ko'rinadi.", max_length=13, validators=[account.validators.validate_phone_number], verbose_name='Aloqa raqami')),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('rating_avg', models.FloatField(db_index=True, default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0, help_text="Denormalizatsiya: ro'yxat so'rovida COUNT(*) qilmaslik uchun.")),
                ('rating_points', models.PositiveIntegerField(db_index=True, default=0, help_text="Barcha sharhlardagi yulduzlar jami. O'rin shunga qarab beriladi.", verbose_name="Yulduzlar yig'indisi")),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, help_text="1 — eng ko'p yulduz yig'gan joy. 0 — hali hisoblanmagan.", verbose_name="O'rin")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-rating_avg', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restoran'), ('venue', "To'yxona")], max_length=15)),
                ('business_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending_payment', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Application',
                'verbose_name_plural': 'Business Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
