# Generated by Django 5.1.3 on 2026-09-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapplication',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Bo'sh — bepul sinov arizasi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='subscriptions.subscriptionplan', verbose_name='Tanlangan tarif'),
        ),
        migrations.AddField(
            model_name='business',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='businesses.businessapplication'),
        ),
        migrations.AddField(
            model_name='businessphoto',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='hall',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='room',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='venuepricing',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='businesses.business'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['status', '-created_at'], name='idx_app_status_created'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['applicant', 'status'], name='idx_app_applicant_status'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_visible', 'business_type', '-rating_avg'], name='idx_biz_visible_type_rating'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_visible', 'district'], name='idx_biz_visible_district'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_visible', 'cuisine'], name='idx_biz_visible_cuisine'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type', '-rating_points'], name='idx_biz_type_points'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_biz_lat_lng'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='idx_biz_owner'),
        ),
        migrations.AddIndex(
            model_name='businessphoto',
            index=models.Index(fields=['business', 'order'], name='idx_bizphoto_business_order'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['business', 'people'], name='idx_hall_business_people'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['business', 'room_type'], name='idx_room_business_type'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['business', 'capacity'], name='idx_room_business_capacity'),
        ),
        migrations.AddConstraint(
            model_name='venuepricing',
            constraint=models.UniqueConstraint(fields=('business', 'dish_count'), name='uniq_venue_pricing_business_dish'),
        ),
    ]
