# Generated by Django 5.2.17 on 2026-09-19 19:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-rating_avg', '-created_at'], 'verbose_name': 'Biznes', 'verbose_name_plural': 'Bizneslar'},
        ),
        migrations.AlterModelOptions(
            name='businessapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Biznes arizasi', 'verbose_name_plural': 'Biznes arizalari'},
        ),
        migrations.AlterModelOptions(
            name='businessphoto',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Biznes rasmi', 'verbose_name_plural': 'Rasm galereyasi'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-people', 'name'], 'verbose_name': 'Zal', 'verbose_name_plural': 'Zallar'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['capacity', 'name'], 'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
        migrations.AlterModelOptions(
            name='venuepricing',
            options={'ordering': ['dish_count'], 'verbose_name': 'Taom paketi narxi', 'verbose_name_plural': 'Taom paketi narxlari'},
        ),
        migrations.AlterField(
            model_name='business',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='business', to='businesses.businessapplication'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='all_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Butun zal uchun bir kunlik qat'iy summa (masalan 15 000 000). Qishloq to'yxonalarida narx odatda shunday: kishi boshiga emas, kunlik ijara. Bo'sh qoldirilsa mijozga narx ko'rsatilmaydi.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bir kunlik ijara narxi'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='deposit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bron qilishda oldindan to'lov. Bo'sh qoldirilsa platforma standarti olinadi.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa, tarifning platformadagi standart narxi olinadi.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
