# Generated by Django 5.1.3 on 2026-09-19 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.business')),
                ('room', models.ForeignKey(blank=True, help_text="Faqat restoran uchun. To'yxona uchun bo'sh qoldiriladi — to'yxonada bo'sh vaqt Room emas, butun business darajasida hisoblanadi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.room')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('guests_count', models.PositiveIntegerField()),
                ('special_request', models.TextField(blank=True)),
                ('dish_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Bir kunlik ijara')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('selected_menu', models.JSONField(blank=True, default=list)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], db_index=True, default='pending', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti')),
                ('availability', models.ForeignKey(blank=True, help_text="Bron tegishli bo'lgan kunlik bo'sh vaqt yozuvi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.availability')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.business')),
                ('hall', models.ForeignKey(blank=True, help_text="Faqat to'yxona broni uchun — qaysi zal band qilingani.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.hall')),
                ('room', models.ForeignKey(blank=True, help_text='Faqat restoran broni uchun.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['business', 'date', 'is_booked'], name='idx_avail_biz_date_booked'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['room', 'date'], name='idx_avail_room_date'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['date', 'is_booked'], name='idx_avail_date_booked'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'date', 'start_time'), name='uniq_room_date_start_time'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', True)), fields=('business', 'date', 'start_time'), name='uniq_business_date_start_time_no_room'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['business', 'status', '-created_at'], name='idx_resv_biz_status_created'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', '-created_at'], name='idx_resv_user_created'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'availability', 'status'], name='idx_resv_room_avail_status'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hall', 'availability', 'status'], name='idx_resv_hall_avail_status'),
        ),
    ]
