# Generated by Django 5.2.17 on 2026-09-19 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_and_more'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': "Bo'sh vaqt", 'verbose_name_plural': "Bo'sh vaqtlar"},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bron', 'verbose_name_plural': 'Bronlar'},
        ),
        migrations.RemoveConstraint(
            model_name='availability',
            name='uniq_business_date_start_time_no_room',
        ),
        migrations.AddField(
            model_name='availability',
            name='hall',
            field=models.ForeignKey(blank=True, help_text="Faqat to'yxona uchun — har bir zal alohida band bo'ladi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.hall'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Faqat restoran uchun.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['hall', 'date'], name='idx_avail_hall_date'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('hall__isnull', False)), fields=('hall', 'date', 'start_time'), name='uniq_hall_date_start_time'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hall__isnull', True), ('room__isnull', False)), models.Q(('hall__isnull', False), ('room__isnull', True)), _connector='OR'), name='chk_avail_room_xor_hall'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('hall__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('availability',), name='uniq_active_hall_reservation'),
        ),
    ]
