# Generated by Django 5.2.17 on 2026-09-20 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_and_more'),
        ('reservations', '0002_alter_availability_options_alter_reservation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availability',
            name='uniq_hall_date_start_time',
        ),
        migrations.RemoveConstraint(
            model_name='availability',
            name='chk_avail_room_xor_hall',
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='uniq_active_hall_reservation',
        ),
        migrations.RemoveIndex(
            model_name='availability',
            name='idx_avail_hall_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='hall',
        ),
        migrations.AlterField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(blank=True, help_text="Faqat restoran uchun. To'yxona uchun bo'sh qoldiriladi — to'yxonada bo'sh vaqt xona emas, butun biznes darajasida hisoblanadi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='businesses.room'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', True)), fields=('business', 'date', 'start_time'), name='uniq_business_date_start_time_no_room'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('hall__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('availability',), name='uniq_active_venue_reservation'),
        ),
    ]
