# Generated by Django 5.2.17 on 2026-09-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sharh', 'verbose_name_plural': 'Sharhlar'},
        ),
        migrations.AlterModelOptions(
            name='reviewphoto',
            options={'ordering': ['created_at'], 'verbose_name': 'Sharh rasmi', 'verbose_name_plural': 'Sharh rasmlari'},
        ),
    ]
