# Generated by Django 5.1.3 on 2026-09-19 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restoran'), ('venue', "To'yxona")], max_length=15)),
                ('duration_months', models.PositiveSmallIntegerField(default=1, help_text='Reja necha oyga amal qiladi. 1 = oylik, 3 = choraklik.', verbose_name='Muddat (oy)')),
                ('price', models.DecimalField(decimal_places=2, help_text="Shu muddat uchun TO'LIQ summa.", max_digits=12, verbose_name='Narx')),
                ('trial_days', models.PositiveIntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Tarif rejasi',
                'verbose_name_plural': 'Tarif rejalari',
                'ordering': ['business_type', 'duration_months'],
                'constraints': [models.UniqueConstraint(fields=('business_type', 'duration_months'), name='uniq_plan_type_duration')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial (bepul)'), ('active', 'Faol'), ('expired', 'Muddati tugagan')], db_index=True, default='trial', max_length=10)),
                ('trial_ends_at', models.DateTimeField()),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_days', models.JSONField(blank=True, default=list, verbose_name='Yuborilgan eslatmalar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='businesses.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending_payment', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Egasining izohi')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='Admin izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='businesses.business')),
                ('plan', models.ForeignKey(help_text='Egasi qaysi muddatni tanlagani.', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='subscriptions.subscriptionplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna arizasi',
                'verbose_name_plural': 'Obuna arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='idx_payment_sub_created')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'trial_ends_at'], name='idx_sub_status_trial_end'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'subscription_ends_at'], name='idx_sub_status_sub_end'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['status', '-created_at'], name='idx_subreq_status_created'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['business', '-created_at'], name='idx_subreq_biz_created'),
        ),
    ]
