# Generated by Django 5.2.17 on 2026-09-19 19:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlog',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lov jurnali"},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obuna', 'verbose_name_plural': 'Obunalar'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Reja necha oyga amal qiladi. 1 = oylik, 3 = choraklik.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Muddat (oy)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Shu muddat uchun TO'LIQ summa.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Narx'),
        ),
    ]
