# Generated by Django 5.2.17 on 2026-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_paymentlog_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Bepul sinov (kun)'),
        ),
    ]
