# Generated by Django 5.1.3 on 2026-09-19 15:56

import common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('starter', "Boshlang'ich"), ('soup', "Sho'rva"), ('main', 'Asosiy taom'), ('salad', 'Salat'), ('dessert', 'Desert'), ('drink', 'Ichimlik'), ('other', 'Boshqa')], db_index=True, default='main', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='restaurant_menu/', validators=[common.validators.validate_image_file])),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_items', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Restaurant Menu Item',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['business', 'is_available'], name='idx_rmenu_business_available'), models.Index(fields=['business', 'category'], name='idx_rmenu_business_category')],
            },
        ),
        migrations.CreateModel(
            name='VenueMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('starter', "Boshlang'ich"), ('soup', "Sho'rva"), ('main', 'Asosiy taom'), ('salad', 'Salat'), ('dessert', 'Desert'), ('drink', 'Ichimlik'), ('other', 'Boshqa')], db_index=True, default='main', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='venue_menu/', validators=[common.validators.validate_image_file])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_menu_items', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Venue Menu Item',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['business', 'category'], name='idx_vmenu_business_category')],
            },
        ),
    ]
