# Generated by Django 5.2.17 on 2026-09-19 19:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_and_more'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantmenuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Restoran taomi', 'verbose_name_plural': 'Restoran menyusi'},
        ),
        migrations.AlterModelOptions(
            name='venuemenuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': "To'yxona taomi", 'verbose_name_plural': "To'yxona menyusi"},
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='business',
            field=models.ForeignKey(limit_choices_to={'business_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_items', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='venuemenuitem',
            name='business',
            field=models.ForeignKey(limit_choices_to={'business_type': 'venue'}, on_delete=django.db.models.deletion.CASCADE, related_name='venue_menu_items', to='businesses.business'),
        ),
    ]
